### ISSUE TITLE
I can't build project

### ISSUE THREAD

**Issue by kolesoffac** [njleonzhang/vue-data-tables#131]
When i run _npm run build_, i have error:
```
ERROR in ./src/index.js
Module build failed: TypeError: Cannot read property 'concat' of undefined
    at visit (/vue-data-tables/node_modules/is-my-json-valid/index.js:366:69)
    at /vue-data-tables/node_modules/is-my-json-valid/index.js:416:9
    at Array.forEach (native)
    at visit (/vue-data-tables/node_modules/is-my-json-valid/index.js:409:18)
    at /vue-data-tables/node_modules/is-my-json-valid/index.js:543:9
    at Array.forEach (native)
    at visit (/vue-data-tables/node_modules/is-my-json-valid/index.js:540:31)
    at compile (/vue-data-tables/node_modules/is-my-json-valid/index.js:565:3)
    at visit (/vue-data-tables/node_modules/is-my-json-valid/index.js:340:16)
    at /vue-data-tables/node_modules/is-my-json-valid/index.js:416:9

```
Actual ver - 3.1.2
with ver. 3.0.1 all good.

How can i repait it?

Thanks

**Comment by kolesoffac** [comment]
Solution:
- back to ver 3.0.1
- npm i
- back to ver 3.1.2
- npm update

**Comment by njleonzhang** [comment]
I suggest you try to use yarn
