### ISSUE TITLE
Cannot build when using data-tables

### ISSUE THREAD

**Issue by johncade** [njleonzhang/vue-data-tables#143]
# Online reproduce
It is important to provide an online sample to reproduce the issue. 

ERROR in ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vue-data-tables/src/components/DataTables.vue
Module build failed: Error: Plugin 1 specified in "C:\\Users\\jogriffin\\WebstormProjects\\sre-page\\node_modules\\vue-data-tables\\.babelrc"
 provided an invalid property of "__wrapped__"
    at Plugin.init (C:\Users\jogriffin\WebstormProjects\sre-page\node_modules\babel-core\lib\transformation\plugin.js:131:13)
    at Function.normalisePlugin (C:\Users\jogriffin\WebstormProjects\sre-page\node_modules\babel-core\lib\transformation\file\options\option-
manager.js:152:12)
    at C:\Users\jogriffin\WebstormProjects\sre-page\node_modules\babel-core\lib\transformation\file\options\option-manager.js:184:30
    at Array.map (native)
    at Function.normalisePlugins (C:\Users\jogriffin\WebstormProjects\sre-page\node_modules\babel-core\lib\transformation\file\options\option
-manager.js:158:20)
    at OptionManager.mergeOptions (C:\Users\jogriffin\WebstormProjects\sre-page\node_modules\babel-core\lib\transformation\file\options\optio
n-manager.js:234:36)
    at OptionManager.init (C:\Users\jogriffin\WebstormProjects\sre-page\node_modules\babel-core\lib\transformation\file\options\option-manage
r.js:368:12)
    at File.initOptions (C:\Users\jogriffin\WebstormProjects\sre-page\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (C:\Users\jogriffin\WebstormProjects\sre-page\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (C:\Users\jogriffin\WebstormProjects\sre-page\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (C:\Users\jogriffin\WebstormProjects\sre-page\node_modules\babel-loader\lib\index.js:50:20)
    at Object.module.exports (C:\Users\jogriffin\WebstormProjects\sre-page\node_modules\babel-loader\lib\index.js:175:20)
 @ ./~/vue-data-tables/src/components/DataTables.vue 6:0-100 7:0-113
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/views/Transparency Dashboard/components/serial-table.vue
 @ ./src/views/Transparency Dashboard/components/serial-table.vue
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/views/Transparency Dashboard/Dashboard.vue
 @ ./src/views/Transparency Dashboard/Dashboard.vue
 @ ./src/router/index.js
 @ ./src/main.js

  Build failed with errors.

**Comment by njleonzhang** [comment]
it seems you directly import `vue-data-tables/src/components/DataTables.vue`, please check the doc https://njleonzhang.github.io/vue-data-tables/#/quickstart?id=import-in-your-project

**Comment by njleonzhang** [comment]
close due to no response
